### ISSUE TITLE
Lower F1 in FactRuEval 2016

### ISSUE THREAD

**Issue by DaniyarM** [deepmipt/ner#15]
Code from training_example achieve only 55 F1 in FactRuEval 2016 (82.10 F1 in your report).
What could be the problem?

**Comment by mshnmshn** [comment]
Embeddings, network architecture, training procedure, hyperparameters. The notebook in the repo is an example but not a comprehensive guide. Moreover, please refer to the current implementation of the deeppavlov.ner (docs.deeppavlov.ai/en/latest/components/ner.html).
