### ISSUE TITLE
FileNotFoundError on Extractor()

### ISSUE THREAD

**Issue by tonko22** [deepmipt/ner#6]
On first time init, i had a ReadError after auto-downloading and extracting ner_model_total_rus.tar.gz:
```
~/speech/lib/python3.5/tarfile.py in open(cls, name, mode, fileobj, bufsize, **kwargs)
   1560                         fileobj.seek(saved_pos)
   1561                     continue
-> 1562             raise ReadError("file could not be opened successfully")
   1563 
   1564         elif ":" in mode:

ReadError: file could not be opened successfully
```

Then, on calling `extractor = ner.Extractor()` i have`FileNotFoundError: [Errno 2] No such file or directory: '/home/user/semantic_venv/lib/python3.5/site-packages/ner/extractor/../model/params.json'`

**Comment by amorgun** [comment]
Looks like something went wrong during downloading. I was a bit lazy with error handling in that part.
As a workaround try `extractor = ner.Extractor(model_path='some_dir_name')`

**Comment by tonko22** [comment]
Downloading [model](http://lnsigo.mipt.ru/export/models/ner/ner_model_total_rus.tar.g) manually solved the problem
