### ISSUE TITLE
Examples are not reproduced

### ISSUE THREAD

**Issue by karelin** [deepmipt/ner#7]
Just installed NER from Gtihub.

The results in example notebook looks corrupted:

> На B-PER
> конспирологическом I-PER
> саммите O
> в B-PER
> США I-PER
> глава O
> Федерального O
> Бюро O
> Расследований O
> сделал O
> невероятное O
> заявление O

Moreover, re-running `example.ipynb` leads to downloading the model again (MD5 sum is wrong). Perhaps, the model was changed on MIPT website?

**Comment by mshnmshn** [comment]
Fixed. Check out
